#!/usr/bin/env bash

npm run lint
if [ $? -ne 0 ]; then
    echo "Linting errors detected. Push rejected."
    exit 1
fi

npm run ts
if [ $? -ne 0 ]; then
    echo "Typescript errors detected. Push rejected."
    exit 1
fi

npm run test